### PR TITLE
[RANCHER-1337, RANCHER-1338, RANCHER-1339, RANCHER-1479]  | keycloak, kong, sidecar custom images build pipelines

### PR DESCRIPTION
**Pull request by eldiiar-duishenaliev**
All testing was completed in: https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/keycloak-image-draft/
Successful build results(keycloak): https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/keycloak-image-draft/19/console
(kong)https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/kong-image-draft/8/console
image

kong:
image
sidecar:
https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/sidecar-image-draft/2/console
image

### CODE REVIEW

**Review by yaroslavishchenko — APPROVED** [review]

**Review by OHaimanov — APPROVED** [review]
As these all 3 pipelines have a same logic/structure, i prefer to move main part into separete lib like (buildDockerImage)

**Review by OHaimanov — CHANGES_REQUESTED** [review]
As these all 3 pipelines have a same logic/structure, i prefer to move main part into separete lib like (buildDockerImage)

**Comment by eldiiar-duishenaliev** [comment]
> As these all 3 pipelines have a same logic/structure, i prefer to move main part into separete lib like (buildDockerImage)

TY Boss for the valuable proposal and comment.
These 3 pipelines are kind of draft variant and later on for sure we'll move main part in some lib.
At this point of time, this PR created with the aim to not block dev process for Eureka base setup.

**Review by OHaimanov — COMMENTED** [review]
As agreed, let's do refactoring in scope of stabilisation. Please create task or doc to track areas where we will need to do refactoring/optimisations?

**Review by OHaimanov — APPROVED** [review]

**Review by epam-avramenko — APPROVED** [review]

**Comment by eldiiar-duishenaliev** [comment]
> As agreed, let's do refactoring in scope of stabilisation. Please create task or doc to track areas where we will need to do refactoring/optimisations?

Sure, Boss, will create a Jira ticket for following up.

**Comment by eldiiar-duishenaliev** [comment]
> > As agreed, let's do refactoring in scope of stabilisation. Please create task or doc to track areas where we will need to do refactoring/optimisations?
> 
> Sure, Boss, will create a Jira ticket for following up.

as follow up the following ticket has been created: https://folio-org.atlassian.net/browse/RANCHER-1502

**Pull request merged**
